CREATE TABLE "TB_PRODUCTS"(

    "PRODUCT_ID" UUID NOT NULL,

    "NAME" CHARACTER VARYING(255),

    "PRICE" NUMERIC(38, 2)

);
ALTER TABLE "TB_PRODUCTS" ADD CONSTRAINT "CONSTRAINT_C" PRIMARY KEY("PRODUCT_ID");